remote_theme: jekyll/minima

title: Cai's Blog
author: 
  name: 蔡天昊 (Cai Tianhao)
  email: caith1234@163.com
  
description: Computer Architecture, Artificial Intelligence and other interesting things.
