theme: minima

title: Cai's Blog
author: 
  name: 蔡天昊 (Cai Tianhao)
  email: caith1234@163.com
  
description: Computer Architecture, Artificial Intelligence and other interesting things.

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed

# Exclude from processing
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
